import{i as n,S as y}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const g="https://pixabay.com/api/",b="37266256-83bd782bb95c33f4401b18249";async function w(s,t){const a=new URLSearchParams({key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}),r=await fetch(`${g}?${a}`);if(!r.ok)throw new Error("Failed to fetch images");return await r.json()}function L(s){const t=document.querySelector(".gallery"),a=s.map(r=>`
      <li class="gallery__item">
        <a href="${r.largeImageURL}">
          <div class="photo-card">
            <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
            <div class="info">
              <p><b>Likes:</b> ${r.likes}</p>
              <p><b>Views:</b> ${r.views}</p>
              <p><b>Comments:</b> ${r.comments}</p>
              <p><b>Downloads:</b> ${r.downloads}</p>
            </div>
          </div>
        </a>
      </li>`).join("");t.insertAdjacentHTML("beforeend",a)}function v(){document.querySelector(".gallery").innerHTML=""}const p=document.querySelector(".form"),S=p.querySelector('input[name="search"]'),q=document.querySelector(".gallery"),f=document.querySelector(".loader"),i=document.querySelector(".load-more");let h="",l=1,u=0,d=null;p.addEventListener("submit",async s=>{s.preventDefault();const t=S.value.trim();if(t===""){n.warning({message:"Please enter a search query.",position:"topRight"});return}h=t,l=1,u=0,v(),i.classList.add("hidden"),await m()});i.addEventListener("click",async()=>{l+=1,await m(!0)});async function m(s=!1){try{f.classList.add("active");const t=await w(h,l);if(u=Math.ceil(t.totalHits/15),t.hits.length===0){s?n.info({message:"You've reached the end of search results.",position:"topRight"}):n.error({message:"Sorry, there are no images matching your search query.",position:"topRight"}),i.classList.add("hidden");return}if(L(t.hits),d?d.refresh():d=new y(".gallery a",{captionsData:"alt",captionDelay:250}),l>=u?i.classList.add("hidden"):i.classList.remove("hidden"),s){const{height:a}=q.firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),i.classList.add("hidden")}finally{f.classList.remove("active")}}
//# sourceMappingURL=index.js.map
